source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'S3TransferUtilitySampleSwift' do
  $awsVersion = '~> 2.13.0'
  pod 'AWSMobileClient', $awsVersion
  pod 'AWSS3', $awsVersion
  pod 'AWSAuthUI', $awsVersion
  pod 'AWSUserPoolsSignIn', $awsVersion 
  pod 'AWSAuthCore', $awsVersion   
end
